### ISSUE TITLE
Rust Source Code

### ISSUE THREAD

**Issue by ghost** [robertmeta/nofrils#29]
There seems to be a problem when using doc comments (///) in rust code. Only when I activate another theme (e.g. nord) and switch back to nofrils doc comments are displayed correctly.

**Comment by moorereason** [comment]
It looks like the [official Rust syntax file](https://github.com/rust-lang/rust.vim/blob/6d5f3d85d1b118d3a74e1f11d45a8b4517e44cc0/syntax/rust.vim#L325) classifies doc comments as `SpecialComment` types, which [nofrils ignores](https://github.com/robertmeta/nofrils/blob/288adeaf32b36c12460f7c801b14cd317e4231ff/colors/nofrils-dark.vim#L115).

A work-around:

```vim
hi rustCommentLineDoc term=NONE cterm=NONE ctermfg=242 ctermbg=NONE gui=NONE guifg=#6C6C6C guibg=NONE
```

From what I can tell, `SpecialComment` is often used to refer to special items inside comments, so nofrils would normally ignore them.  But since the entire Rust doc comment block is a `SpecialComment`, it's not being treated as a comment.

Nofrils should probably highlight a `SpecialComment` the same as a `Comment`.

**Comment by ghost** [comment]
That was quick. Thanks a lot Cameron. Hope it gets merged soon.
